### ISSUE TITLE
`media_button` method triggers a PHP Notice (property of non-object)

### ISSUE THREAD

**Issue by lisaleague** [raventools/schema-creator#113]
With debug on, I'm getting multiple php notices for the same line:

![screenshot-mail google com 2014-12-11 11-14-53](https://cloud.githubusercontent.com/assets/3607365/5397257/0696eb8e-8127-11e4-9cf4-7057e438fb3f.png)

**Comment by stephenyeargin** [comment]
I'm going to guess you're using the general release of the plugin rather what's currently here in the `master` branch. I added some tags in recently that will let us jump back to that version for debugging:

https://github.com/raventools/schema-creator/blob/1.050/schema-creator.php#L1397

It's generally not advisable to have that level of debugging enabled in a production environment. That said, our code should be error-free in any case. This is a legitimate bug that should be addressed with  a check to confirm `get_current_screen()` returns an object before being tested against.

**Comment by lisaleague** [comment]
Yes @stephenyeargin using the general release while the site was in dev at that time.
