### ISSUE TITLE
WordPress plugin page says the plugin is only compatible up to 3.6.1

### ISSUE THREAD

**Issue by heatherdnewton** [raventools/schema-creator#122]
Hello,

I would like to get started using this plugin, but our lead developer is nervous about the inactivity on the WP plugin page over the last year and a half.  Can you explain your current approach to supporting this plugin?  Do you simply prefer that everyone just ignore the download available on https://wordpress.org/plugins/schema-creator/ and use whatever you have as the latest on GitHub?  If so,  up to what version of WP is this plugin really compatible?  

Thank you!

**Comment by stephenyeargin** [comment]
Your developer is right that we haven't shipped any changes to the plugin repository in a while, but the plugin is still in active development. We are aiming to get a `1.1.0` release together in the near term. When that version is finalized, it will be posted to the official plugin repository.

The plugin has been tested against WordPress 4.1.1 (latest public release) and we aren't aware of any breaking changes specific to newer versions of WordPress.

**Comment by stephenyeargin** [comment]
We've shipped version 1.1.1 with some minor updates. Thanks for reaching out.

https://wordpress.org/plugins/schema-creator/changelog/

**Comment by heatherdnewton** [comment]
Thanks very much!
