### ISSUE TITLE
Schema- visable on post

### ISSUE THREAD

**Issue by gogeiger** [raventools/schema-creator#131]
Here is the link that shows the code on published page.
http://www.elitehvaccontractors.com/malvern-pa/

How do I have it embedded but not visible?

Is it designed to be this way?

Thanks,
Tim

**Comment by stephenyeargin** [comment]
See #82 and 43. The plugin is intended to help structure data that is rendered on the page.

**Comment by gogeiger** [comment]
Stephen,

 

I appreciate you letting me know. Is it best as I placed it or another location?

 

Thank you, 

 

cid:image012.jpg@01CBE48C.48CF7160

 

Timothy Geiger
