### ISSUE TITLE
Schema is visibly showing on page

### ISSUE THREAD

**Issue by StatManDu** [raventools/schema-creator#133]
Why is my schema data visibly showing on the page? Is it a theme issue? What can be done to rectify this so that I can use the tool? Thank you!

![image](https://cloud.githubusercontent.com/assets/13544829/8942892/874731ce-353d-11e5-975f-62fd52f6885b.png)

**Comment by stephenyeargin** [comment]
This particular plugin is purposefully designed to render the shema data. You can optionally apply CSS to the rendered content to alter how it is displayed (including hiding it). We do not have native support for that, however.

Related: #104 and #78

**Comment by StatManDu** [comment]
OK. Thank you for your quick response, Stephen.

Morgan

On Tue, Jul 28, 2015 at 3:33 PM, Stephen Yeargin <notifications@github.com>
wrote:

> This particular plugin is purposefully designed to render the shema data.
> You can optionally apply CSS to the rendered content to alter how it is
> displayed (including hiding it). We do not have native support for that,
> however.
>
> Related: #104 <https://github.com/raventools/schema-creator/issues/104>
> and #78 <https://github.com/raventools/schema-creator/issues/78>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/raventools/schema-creator/issues/133#issuecomment-125745939>
> .
>



-- 
Morgan Arnold
Owner, Fastball Internet Marketing Solutions
(214) 502-1153
